#!/bin/bash
[ -z $1 ] && echo "usage: record-video <format>" && exit 1
FORMAT=$1
trap "pkill ffmpeg" INT
FFMPEG_PID=$(pidof ffmpeg)
if [ $? -eq 0 ]
then
    kill $FFMPEG_PID
    exit
fi

FPS=15
FILE=$(mktemp -t record$FORMAT.XXXXXXXXXXXX.$FORMAT)
FILENAME=$(basename $FILE)

COORDINATES=$(xrectsel "-video_size %wx%h -i $DISPLAY+%x,%y")
if [ $? -ne 0 ]; then exit; fi

ERROR=$(ffmpeg -loglevel quiet -y -f x11grab $COORDINATES -framerate $FPS "$FILE")
if [[ $? -ne 0 && $? -ne 255 ]]
then
    notify-send "Recording failed. $ERROR"
    exit
fi

FILTER="Video (${FORMAT}) | *.${FORMAT}"
TARGET_FILE=$(zenity --file-selection --file-filter="$FILTER" --save --filename=$FILENAME --confirm-overwrite)
if [ $? -ne 0 ]
then
    rm $FILE
    exit
fi

mv $FILE $TARGET_FILE
notify-send "Saved as $TARGET_FILE"
